---
tenants:
  type: "object"
  required: true
  patternProperties:
    "^\\w+":
      "$ref": "#/properties/credentials"
  additionalProperties: false

tenant_credentials:
  type: "object"
  properties:
    tenant_value:
      description: "Cylance Tenant Value"
      type: "string"
      secret: false
      required: true
    app_id:
      description: "Cylance Application Id"
      type: "string"
      secret: false  
      required: true
    app_secret:
      description: "Application Secret"
      type: "string"
      secret: false
      required: true
  additionalProperties: false